# Stage 1: Build with Maven
FROM maven:3.9.11-eclipse-temurin-26 AS builder
WORKDIR /app
COPY pom.xml ./
COPY .mvn ./.mvn
COPY mvnw ./
COPY src ./src
RUN ./mvnw clean package -DskipTests

# Stage 2: Run with Java
FROM eclipse-temurin:26-jre
WORKDIR /app
COPY --from=builder /app/target/*.jar app.jar
ENTRYPOINT ["java", "-jar", "app.jar"]